name: Monitor Algoverse

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Attempt to restore seen_ids.json
        continue-on-error: true
        run: |
          mkdir -p restore
          cd restore
          gh run download --name seen-data || echo "No artifact yet"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move seen_ids.json if exists
        run: |
          if [ -f restore/seen_ids.json ]; then
            mv restore/seen_ids.json seen_ids.json
          fi

      - name: Run monitoring script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: python main.py

      - name: Upload seen_ids.json
        uses: actions/upload-artifact@v4
        with:
          name: seen-data
          path: seen_ids.json
