name: Daily Algoverse Alert

on:
  schedule:
    - cron: '0 15 * * *'  # Runs daily at 8AM PST (15:00 UTC)
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest

    env:
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_AGENT: ${{ secrets.REDDIT_AGENT }}
      TWITTER_BEARER: ${{ secrets.TWITTER_BEARER }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug environment (sanitized)
        run: |
          echo "🔍 DEBUG ENVIRONMENT"
          echo "REDDIT_AGENT=${REDDIT_AGENT:+[SET]}"
          echo "REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID:+[SET]}"
          echo "TWITTER_BEARER=${TWITTER_BEARER:+[SET]}"
          echo "SLACK_WEBHOOK=${SLACK_WEBHOOK:+[SET]}"

      - name: Run main script
        run: python main.py
